Streamline use of the word "application" in UI
neo42-GmbH/PSAppDeployToolKitExtensions pull request #1106
Opened 2024-10-14 11:38 UTC by neo42JBR

This PR will fix the use of the word "application". 

Previously different types have been used such as:
* Application
* Process
* Program
etc

2024-10-15 12:46 UTC, neo42mgn requested changes

2024-10-15 12:46 UTC, neo42mgn commented on AppDeployToolkit/AppDeployToolkitConfig.xml
>  		<NxtWelcomePrompt_ApplicationClose>Die folgenden Programme müssen geschlossen werden, bevor die {0} fortgesetzt werden kann.</NxtWelcomePrompt_ApplicationClose>
das auch noch

2024-10-23 09:28 UTC, neo42man approved these changes

2024-10-31 11:29 UTC, neo42mgn approved these changes

2024-10-31 11:30 UTC, merged