PSADT 3.10.2
neo42-GmbH/PSAppDeployToolKitExtensions pull request #951
Opened 2024-06-26 12:22 UTC by neo42JBR

Import new and updated values from 3.10.1 release of PSADT.
Sensible defaults for new values have been selected.

Values can be adjusted in downstream PRs

2024-11-29 13:32 UTC, neo42mgn requested changes

2024-11-29 13:32 UTC, neo42mgn commented on AppDeployToolkit/AppDeployToolkitConfig.xml
> +		<Config_Version>3.10.1</Config_Version>
3.10.2

2024-11-29 13:32 UTC, neo42mgn commented on AppDeployToolkit/AppDeployToolkitConfig.xml
> +		<NxtWelcomePrompt_FollowApplication>La seguente applicazione sta per essere {0}:</NxtWelcomePrompt_FollowApplication>
Move all the translations to a different issue, branch and PR, only en and de in this PR

2024-11-29 13:32 UTC, neo42mgn commented on AppDeployToolkit/AppDeployToolkitConfig.xml
>  		<NxtWelcomePrompt_DeferalExpired>Once the defferal is expired, you will no longer have the option to defer.</NxtWelcomePrompt_DeferalExpired>
also here: defferal -> deferal

2024-12-12 11:10 UTC, neo42mgn requested changes

2024-12-12 11:10 UTC, neo42mgn commented on AppDeployToolkit/AppDeployToolkitConfig.xml
> +        <closePrompt_CountdownMessage>NOTA: El/los programa(s) se cerrará(n) automáticamente en:</closePrompt_CountdownMessage>
use tab instead of 4 whitespaces and start with capital letter

2024-12-12 14:01 UTC, neo42JBR commented on AppDeployToolkit/AppDeployToolkitConfig.xml
> +        <closePrompt_CountdownMessage>NOTA: El/los programa(s) se cerrará(n) automáticamente en:</closePrompt_CountdownMessage>
Was in upstream. Fixed anyway

2024-12-12 16:07 UTC, neo42mgn approved these changes

2024-12-12 16:07 UTC, merged