921 add all properties of neo42packageconfig to schema
neo42-GmbH/PSAppDeployToolKitExtensions pull request #997
Opened 2024-08-28 07:36 UTC by neo42JBR

2024-09-19 09:39 UTC, neo42mgn requested changes

2024-10-07 12:32 UTC, neo42JBR commented on test/schemas/neo42PackageConfig.schema.json
> +			"$ref": "#/$defs/NeoGUID",
Already is. Refer to /$defs/NeoGUID

2024-10-07 12:34 UTC, neo42JBR commented on test/schemas/neo42PackageConfig.schema.json
> +		"InstallMethod": {
Already should align with documentation. Refer to /$defs/InstallMethod

2024-10-08 13:20 UTC, neo42mgn approved these changes

2024-10-08 13:31 UTC, merged